import { Category, TransactionWithCategory, Profile } from '../types';

export const mockCategories: Category[] = [
  {
    id: '1',
    user_id: 'mock-user',
    name: 'Transportation',
    color: '#FF6B6B',
    icon: 'car',
    is_default: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    user_id: 'mock-user',
    name: 'Food',
    color: '#4ECDC4',
    icon: 'restaurant',
    is_default: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    user_id: 'mock-user',
    name: 'Clothes',
    color: '#45B7D1',
    icon: 'shirt',
    is_default: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    user_id: 'mock-user',
    name: 'Gadget',
    color: '#96CEB4',
    icon: 'laptop',
    is_default: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    user_id: 'mock-user',
    name: 'Grocery',
    color: '#FFEAA7',
    icon: 'shopping-cart',
    is_default: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    user_id: 'mock-user',
    name: 'Rent',
    color: '#DDA0DD',
    icon: 'home',
    is_default: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    user_id: 'mock-user',
    name: 'Bills',
    color: '#98D8C8',
    icon: 'file-text',
    is_default: true,
    created_at: new Date().toISOString(),
  },
];

export const mockTransactions: TransactionWithCategory[] = [
  {
    id: '1',
    user_id: 'mock-user',
    type: 'expense',
    category_id: '1',
    amount: 45.50,
    description: 'Uber ride to work',
    importance: 'essential',
    transaction_date: new Date().toISOString().split('T')[0],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[0],
  },
  {
    id: '2',
    user_id: 'mock-user',
    type: 'expense',
    category_id: '2',
    amount: 23.75,
    description: 'Lunch at Chipotle',
    importance: 'essential',
    transaction_date: new Date().toISOString().split('T')[0],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[1],
  },
  {
    id: '3',
    user_id: 'mock-user',
    type: 'income',
    category_id: '1',
    amount: 2500.00,
    description: 'Monthly salary',
    transaction_date: new Date().toISOString().split('T')[0],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[0],
  },
];

export const mockProfile: Profile = {
  id: 'mock-user',
  email: 'user@example.com',
  full_name: 'John Doe',
  avatar_url: undefined,
  currency: 'THB',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}; 